services:
    db:
        image: mysql:8.0
        container_name: fastify_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db_data:/var/lib/mysql
    app:
        build: .
        container_name: fastify_app
        restart: always
        ports:
            - "${PORT}:${PORT}"
        environment:
            DB_HOST: db
        depends_on:
            - db
        volumes:
            - ./src:/app/src
            - /app/node_modules
        env_file:
            - .env
    localstack:
        image: localstack/localstack:4.9
        container_name: localstack
        ports:
            - "4566:4566"
        environment:
            SERVICES: "s3"
            DEBUG: "1"
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

volumes:
    db_data:
