services:
    db:
        image: mysql:8.0
        container_name: fastify_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db_data:/var/lib/mysql
    app:
        build: .
        container_name: fastify_app
        restart: always
        ports:
            - "${PORT}:${PORT}"
        environment:
            PORT: ${PORT}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db
        volumes:
            - .:/app
            - /app/node_modules

volumes:
    db_data:
